# Generated by Django 3.1.7 on 2021-03-02 10:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210226_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilePic',
            field=models.ImageField(blank=True, default='employee/profile-picture.png', null=True, upload_to=accounts.models.documents_path),
        ),
    ]
