# Generated by Django 3.1.7 on 2021-03-08 10:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210304_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilePic',
            field=models.ImageField(default='employee/profile-picture.png', upload_to=accounts.models.documents_path),
        ),
    ]
