# Generated by Django 3.1.7 on 2021-03-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20210304_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppa', models.IntegerField()),
                ('monthly_salary', models.IntegerField()),
                ('basic_da', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('conveyance', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('esic', models.IntegerField()),
                ('professional_tax', models.IntegerField()),
                ('net_salary', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('paid_status', models.BooleanField(default=False)),
                ('paid_date', models.DateField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'monthly_salary',
            },
        ),
    ]
