# Generated by Django 3.1.7 on 2021-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_date',
            field=models.DateField(),
        ),
    ]
